export const AUTENTICAR = 'AUTENTICAR';
export const CONECTAR = 'CONECTAR';
export const RECUPERAR_SENHA = 'RECUPERAR_SENHA';
export const ALTERAR_SENHA = 'ALTERAR_SENHA';
export const VALIDAR_EMAIL = 'VALIDAR_EMAIL';
export const CHECAR_SIMBOLO_EMAIL = 'CHECAR_SIMBOLO_EMAIL';
export const CRIAR_CONTA = 'CRIAR_CONTA';
export const CONECTAR_FACEBOOK = 'CONECTAR_FACEBOOK';