export const COLETA_NOVA = 'nova_coleta';
export const COLETA_NOVA_TEMPO_EXPIRADO = 'COLETA_NOVA_TEMPO_EXPIRADO';
export const COLETA_ACEITA = 'COLETA_ACEITA';
export const COLETA_ATUALIZAR_STATUS = 'COLETA_ATUALIZAR_STATUS';
export const COLETA_CHECKIN = 'COLETA_CHECKIN';
export const COLETA_LIMPAR = 'COLETA_LIMPAR';
