export const BUSCAR_DISPONIBILIDADE = 'BUSCAR_DISPONIBILIDADE';
export const TOOGLE_SELECT_DISPONIBILIDADE = 'TOOGLE_SELECT_DISPONIBILIDADE';
export const SALVAR_DISPONIBILIDADE = 'SALVAR_DISPONIBILIDADE';
export const MUDAR_DE_ABA_EM_DISPONIBILIDADE = 'MUDAR_DE_ABA_EM_DISPONIBILIDADE';